# Generated by Django 3.2 on 2022-01-27 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionDoctors',
            fields=[
                ('direction_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID направления')),
                ('direction_doctors', models.CharField(max_length=100, verbose_name='Направление врача')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='RegistryEmployee',
            fields=[
                ('red_empl_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID сотрудника')),
                ('bd', models.DateField(verbose_name='Дата рождения сотрудника')),
                ('post', models.CharField(max_length=100, verbose_name='Должность сотрудника')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник регистратуры',
                'verbose_name_plural': 'Сотрудники регистратуры',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID пациента')),
                ('bd', models.DateField(verbose_name='Дата рождения пациента')),
                ('policy', models.CharField(max_length=16, verbose_name='Полис')),
                ('passport', models.CharField(max_length=10, verbose_name='Паспорт')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID врача')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО врача')),
                ('cab', models.CharField(default='', max_length=3, verbose_name='Номер кабинета')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.directiondoctors', verbose_name='Напрвление врача')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('coupons_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID талона')),
                ('adm_date', models.DateTimeField(verbose_name='Дата посещения')),
                ('adm_date_end', models.DateTimeField(verbose_name='Время окончания приема')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.doctors', verbose_name='Врач')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.patients', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Талон',
                'verbose_name_plural': 'Талоны',
            },
        ),
    ]
