# Generated by Django 3.2 on 2022-01-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='cab',
            field=models.CharField(default='', max_length=3, verbose_name='Номер кабинета'),
        ),
    ]
